file1= open ('codes/Module 5 - Files, Exceptions and Errors/sample.txt', 'r+')
data = file1.read()
write_data = input("Enter text to Write in the file: ")
file1.write(write_data)
print("Data written to file successfully.")
write_data1 = input("Enter text to Append in the file: ")
file1.write(write_data1)
print("Final content of sample.txt: ")
print(write_data.strip())
print(write_data1.strip())
# file1.seek(0)
# print(file1.readlines(1))
file1.close()